# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qDX3itwIDgdmBNosxfXrGzHV07N1aEw
"""
import streamlit as st
import numpy as np
from PIL import Image
import joblib
import time

# =====================================
# Page Configuration
# =====================================
st.set_page_config(
    page_title="AI Gender Classifier",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded"
)

# =====================================
# Sidebar
# =====================================
with st.sidebar:

    st.image(
        "https://img.icons8.com/color/480/artificial-intelligence.png",
        width=110
    )

    st.title("🧠 AI Gender Classifier")

    dark_mode = st.toggle("🌙 Dark Mode")

    st.markdown("---")

    st.markdown("### 💡 AI Tips")

    st.info("""
✔ Use a clear face image  
✔ Front-facing face  
✔ Good lighting  
✔ JPG / PNG format  
""")

    st.markdown("---")

    st.markdown("### 🛠 Tech Stack")

    st.write("🐍 Python")
    st.write("🎈 Streamlit")
    st.write("🧠 Scikit-Learn")
    st.write("🖼 Pillow")
    st.write("📊 NumPy")

    st.markdown("---")

    st.success("Made with ❤️ by Akanksha Mishra")

# =====================================
# Theme Colors
# =====================================
if dark_mode:
    bg = "#0F0F0F"
    card = "#1A1A1A"
    text = "#FAFAFA"
else:
    bg = "#FAFAFA"
    card = "#FFFFFF"
    text = "#262626"

# =====================================
# Custom CSS
# =====================================
st.markdown(f"""
<style>

/* App Background */
.stApp {{
    background-color:{bg};
    color:{text};
}}

/* Sidebar */
section[data-testid="stSidebar"] {{
    background-color:{card};
    border-right:2px solid #3B82F6;
}}

section[data-testid="stSidebar"] * {{
    color:{text} !important;
}}

/* Text */
h1,h2,h3,h4,h5,h6,p,span,label {{
    color:{text};
}}

/* File Uploader */
div[data-testid="stFileUploader"] {{
    background-color:{"#1E293B" if dark_mode else "#FFFFFF"};
    border:2px dashed #E1306C;
    border-radius:15px;
    padding:15px;
}}

div[data-testid="stFileUploader"] * {{
    color:{"white" if dark_mode else "black"} !important;
}}

div[data-testid="stFileUploader"] button {{
    background:linear-gradient(
135deg,
#833AB4,
#FD1D1D,
#F77737
) !important;
    color:white !important;
    border-radius:8px;
}}

</style>
""", unsafe_allow_html=True)

# =====================================
# Load Model
# =====================================
model = joblib.load("male_female_model.pkl")
IMG_SIZE = 64

# =====================================
# Header
# =====================================
st.markdown(f"""
<div style="
background: linear-gradient(
    135deg,
    #833AB4,
    #FD1D1D,
    #F77737,
    #FCAF45
);
padding:18px;
border-radius:15px;
text-align:center;
color:white;
">

<h2>🧠 AI Gender Classification System</h2>

<p style="font-size:15px;">
Upload a face image and predict Male or Female using AI
</p>

</div>
""", unsafe_allow_html=True)

st.write("")

st.info("📸 Upload a clear face image for best results.")

# =====================================
# Upload Image
# =====================================
uploaded_file = st.file_uploader(
    "Choose an Image",
    type=["jpg", "jpeg", "png"]
)

# =====================================
# Prediction
# =====================================
if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")

    col1, col2 = st.columns(2)

    # -------------------------
    # Show Image
    # -------------------------
    with col1:
        st.image(image, use_container_width=True)

    # -------------------------
    # Preprocess Image
    # -------------------------
    img = image.resize((IMG_SIZE, IMG_SIZE))
    img = np.array(img).flatten()

    # -------------------------
    # Prediction
    # -------------------------
    with st.spinner("🤖 AI is analyzing the image..."):
        time.sleep(1.5)

        prediction = model.predict([img])[0]
        probability = model.predict_proba([img])[0]

    # -------------------------
    # Result Logic
    # -------------------------
    if prediction == 0:
        result = "👩 Female"
        confidence = probability[0] * 100
        color = "#E1306C"
    else:
        result = "👨 Male"
        confidence = probability[1] * 100
        color = "#833AB4"

    # -------------------------
    # Right Side UI
    # -------------------------
    with col2:

        st.markdown(f"""
        <div style="
        background:{color};
        padding:25px;
        border-radius:15px;
        text-align:center;
        color:white;
        box-shadow:0px 4px 12px rgba(0,0,0,0.25);
        ">

        <h2>🎯 Prediction Result</h2>

        <h1>{result}</h1>

        </div>
        """, unsafe_allow_html=True)

        st.write("")

        st.markdown(f"""
        <div style="
        background:{card};
        padding:20px;
        border-radius:15px;
        border-left:6px solid #2563EB;
        box-shadow:0px 3px 8px rgba(0,0,0,0.12);
        ">

        <h3 style="color:{text};">📊 Model Confidence</h3>

        <h1 style="color:#2563EB;">{confidence:.2f}%</h1>

        </div>
        """, unsafe_allow_html=True)

        st.toast("Prediction Completed 🎉", icon="✅")

        # -------------------------
        # Download Report
        # -------------------------
        report = f"""
AI Gender Classification Report

Prediction: {result}

Confidence: {confidence:.2f}%
"""

        st.download_button(
            "📄 Download Report",
            report,
            file_name="Prediction_Report.txt"
        )



