# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qDX3itwIDgdmBNosxfXrGzHV07N1aEw
"""

import streamlit as st
import numpy as np
from PIL import Image
import joblib
import time

# =====================================
# Page Configuration
# =====================================
st.set_page_config(
    page_title="AI Gender Classifier",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded"
)

# =====================================
# Sidebar
# =====================================


with st.sidebar:

    st.image(
        "https://img.icons8.com/color/480/artificial-intelligence.png",
        width=110
    )

    st.title("🧠 AI Gender Classifier")

    dark_mode = st.toggle("🌙 Dark Mode")

    st.markdown("---")

    st.markdown("### 💡 AI Tips")

    st.info("""
✔ Use a clear face image  
✔ Front-facing face  
✔ Good lighting  
✔ JPG / PNG format  
""")

    st.markdown("---")

    st.markdown("### 🛠 Tech Stack")

    st.write("🐍 Python")
    st.write("🎈 Streamlit")
    st.write("🧠 Scikit-Learn")
    st.write("🖼 Pillow")
    st.write("📊 NumPy")

    st.markdown("---")

    st.success("Made with ❤️ by Akanksha Mishra")
    
# =====================================
# Theme Colors
# =====================================
if dark_mode:
    bg = "#0B1220"
    card = "#1B2430"
    text = "#F8FAFC"
else:
    bg = "#F5F7FA"
    card = "#FFFFFF"
    text = "#111827"

# =====================================
# Custom CSS
# =====================================
st.markdown(f"""
<style>

.stApp {{
    background-color:{bg};
    color:{text};
}}

section[data-testid="stSidebar"] {{
    background-color:{card};
    border-right:2px solid #3B82F6;
}}

section[data-testid="stSidebar"] * {{
    color:{text} !important;
}}

h1,h2,h3,h4,h5,h6,p,span,label {{
    color:{text};
}}

div[data-testid="stFileUploader"] {{
    background-color:{"#1E293B" if dark_mode else "#FFFFFF"};
    border:2px dashed #60A5FA;
    border-radius:15px;
    padding:15px;
}}

div[data-testid="stFileUploader"] * {{
    color:{"white" if dark_mode else "black"} !important;
}}

div[data-testid="stFileUploader"] button {{
    background:#2563EB !important;
    color:white !important;
    border-radius:8px;
}}

</style>
""", unsafe_allow_html=True)

# =====================================
# Load Model
# =====================================
model = joblib.load("male_female_model.pkl")
IMG_SIZE = 64

# =====================================
# Header
# =====================================
st.markdown("""
<div style="
background: linear-gradient(90deg,#2563EB,#1D4ED8);
padding:15px;
border-radius:12px;
text-align:center;
color:white;
">

<h2>🧠 AI Gender Classification System</h2>

<p>
Upload a face image and let AI predict Male or Female.
</p>

</div>
""", unsafe_allow_html=True)

st.info("📸 Upload a clear, front-facing face image for best results.")

# =====================================
# Upload Image
# =====================================
uploaded_file = st.file_uploader(
    "Choose an Image",
    type=["jpg", "jpeg", "png"]
)

# =====================================
# Prediction
# =====================================
if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")

    col1, col2 = st.columns(2)

    with col1:
        st.image(image, caption="Uploaded Image", use_container_width=True)

    img = image.resize((IMG_SIZE, IMG_SIZE))
    img = np.array(img).flatten()

    with st.spinner("🤖 AI is analyzing..."):
        time.sleep(1.5)
        prediction = model.predict([img])[0]
        probability = model.predict_proba([img])[0]

    if prediction == 0:
        result = "👩 Female"
        confidence = probability[0] * 100
        color = "#22C55E"
    else:
        result = "👨 Male"
        confidence = probability[1] * 100
        color = "#2563EB"

    with col2:
        st.markdown(f"""
        <div style="
        background:{color};
        padding:25px;
        border-radius:15px;
        text-align:center;
        color:white;
        ">
        <h2>🎯 Prediction</h2>
        <h1>{result}</h1>
        </div>
        """, unsafe_allow_html=True)

        st.markdown(f"""
        <div style="
        background:{card};
        padding:20px;
        border-radius:15px;
        border-left:6px solid #2563EB;
        ">
        <h3>📊 Confidence</h3>
        <h1 style="color:#2563EB;">{confidence:.2f}%</h1>
        </div>
        """, unsafe_allow_html=True)

        st.toast("Prediction Completed 🎉", icon="✅")

        report = f"""
Prediction Report

Result: {result}
Confidence: {confidence:.2f}%
"""

        st.download_button(
            "📄 Download Report",
            report,
            file_name="report.txt"
        )

# =====================================
# Footer Info
# =====================================
st.markdown("""
<div style="text-align:center;padding:15px;">

<h4>🧠 AI Gender Classification System</h4>

<p>
Developed using <b>Python</b> • <b>Streamlit</b> • <b>Scikit-Learn</b> • <b>NumPy</b> • <b>Pillow</b>
</p>

<div style="display:flex; justify-content:center; gap:20px; margin-top:10px;">

    <a href="https://github.com/Akanksha549/" target="_blank">
        <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg" width="35">
    </a>

    <a href="https://www.linkedin.com/in/akanksha-mishra-7894912bb" target="_blank">
        <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-original.svg" width="35">
    </a>

</div>

<p style="color:gray; margin-top:10px;">
© 2026 AI Project
</p>

</div>
""", unsafe_allow_html=True)
